config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :alumns do
    
    resources :comments
  end
  devise_for :users

  get 'show_list'=> "alumns#show_list",:as => "show_list"
  get 'show_timetable'=> "alumns#show_timetable",:as => "show_timetable"
  get 'show_resources'=> "alumns#show_resources",:as => "show_resources"


  get 'show_list_category'=> "categories#show_list_category",:as => "show_list_category"
  get 'show_menu'=> "categories#show_menu",:as => "show_menu"
  get 'show_timetable_comedor'=> "categories#show_timetable_comedor",:as => "show_timetable_comedor"
  get 'show_timetable_madrugadores'=> "categories#show_timetable_madrugadores",:as => "show_madrugadores"
  get 'show_timetable_tardones'=> "categories#show_timetable_tardones",:as => "show_timetable_tardones"
  get 'activities'=> "categories#activities",:as => "activities"
  get 'activities_tardones'=> "categories#activities_tardones",:as => "activities_tardones"
  get 'docs'=> "categories#docs",:as => "docs"

  #Esto es similar a escribir:
	  #get "/alumns" index
	  #post "/alumns" create
	  #delete "/alumns" delete
	  #get "/alumns/:id" show
	  #get "/alumns/new" new
	  #get "/alumns/:id/edit" edit
	  #patch "/alumns/:id" update
	  #put "/alumns/:id" update
  #
  #
  #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :alumn
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_alumn#, only: [:show, :edit, :update, :destroy]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params) 
    @comment.alumn = @alumn
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @alumn, notice: 'Comentario añadido correctamente' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.alumn, notice: 'Comentario añadido correctamente' }
        format.json { render :show, status: :created, location: @comment.alumn }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    #@alumn = Alumn.find(params[:alumn_id])
    #@comment = @alumn.comments.find(params[:id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @alumn, notice: 'Comentario eliminado correctamente' }
      format.json { head :no_content }
    end
  end

  private
  def set_alumn
      @alumn = Alumn.find(params[:alumn_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :alumn_id, :body)
    end

    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@alumn,@comment]) do |form| %>
 <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="actions">
    <%= form.submit "Nuevo", class: "btn-primary", style: "padding: 5px;" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice text" style="text-align: center;"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Alumn:</strong>
  <%= @comment.alumn %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>