config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :alumns do
    
    resources :comments
  end
  devise_for :users

  get 'show_list'=> "alumns#show_list",:as => "show_list"
  get 'show_timetable'=> "alumns#show_timetable",:as => "show_timetable"
  get 'show_resources'=> "alumns#show_resources",:as => "show_resources"


  get 'show_list_category'=> "categories#show_list_category",:as => "show_list_category"
  get 'show_menu'=> "categories#show_menu",:as => "show_menu"
  get 'show_timetable_comedor'=> "categories#show_timetable_comedor",:as => "show_timetable_comedor"
  get 'show_timetable_madrugadores'=> "categories#show_timetable_madrugadores",:as => "show_madrugadores"
  get 'show_timetable_tardones'=> "categories#show_timetable_tardones",:as => "show_timetable_tardones"
  get 'activities'=> "categories#activities",:as => "activities"
  get 'activities_tardones'=> "categories#activities_tardones",:as => "activities_tardones"
  get 'docs'=> "categories#docs",:as => "docs"

  #Esto es similar a escribir:
	  #get "/alumns" index
	  #post "/alumns" create
	  #delete "/alumns" delete
	  #get "/alumns/:id" show
	  #get "/alumns/new" new
	  #get "/alumns/:id/edit" edit
	  #patch "/alumns/:id" update
	  #put "/alumns/:id" update
  #
  #
  #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/partials/_footer.html.erb
<footer>
	<div class="row center-xs">
		<p class="footer">© GesClass SL. C/ Peña de Francia, 41. Bajo. 37007. Salamanca</p>

	</div>
	<div class="row">
        <div class="col-sm-6 center-xs">
            <h3 class="footer_title">Contacta con nosotros:</h3>
            <p class="footer_data">+34 911 111 111</p>
            <p class="footer_data">gesclass@ejemplo.com</p>
        </div>
        <div class="col-sm-6 center-xs">
            <h3 class="footer_title">Síguenos en:</h3>
            <a href="http://twitter.com/AQUI_TU_USUARIO" target="_blank"><img src="https://lh6.googleusercontent.com/--aIk2uBwEKM/T3nN1x09jBI/AAAAAAAAAs8/qzDsbw3kEm8/s32/twitter32.png" width=40 height=40 alt="Síguenos en Twitter"/></a>
            <a href="http://www.facebook.com/AQUI_TU_PAGINA" target="_blank"><img alt="Siguenos en Facebook" src="https://lh6.googleusercontent.com/-CYt37hfDnQ8/T3nNydojf_I/AAAAAAAAAr0/P5OtlZxV4rk/s32/facebook32.png" width=40 height=40/></a>
            <a rel="author" href="https://plus.google.com/TU_ID_GOOGLE?rel=author" target="_blank"><img alt="Siguenos en Google+" src="https://lh5.googleusercontent.com/-F_FBKktZWZk/T3nN0v4FeAI/AAAAAAAAAsc/7dHTxkxn4cI/s32/google32.png" width=40 height=40/></a>
        	<a href="URL_DE_TU_PERFIL_INSTAGRAM" target="_blank"><img alt="Siguenos en Blogger" src="https://lh5.googleusercontent.com/-vBqtz2iv2BE/UIqE3LQyFMI/AAAAAAAABgA/TJ4W-vIBjsc/s32/instagram32.png" width=40 height=40/></a>
		</div>
	</div>
</footer>

app/views/partials/_header.html.erb
<header>
	<div class="row">
		<%= image_tag("infantil-header.jpg", :alt => "Header", :style => "width:100%; height: 310px;") %>
		<%= render "partials/navigation" %>
	</div>
</header>

app/views/partials/_navigation.html.erb
<nav class="white col-md-12">
	<ul class="no-list row center-xs">
		<li class="col-md auto-margin div-rotate">
			<%=link_to "Inicio", root_path, :class =>"rotate"%>
		</li>
    <li class="col-md auto-margin div-rotate">
      <%= link_to "Gestión", alumns_path, :class =>"rotate" %>
    </li>
    <% @categories.each do |category|%>
		<li class="col-md auto-margin div-rotate">
			<%= link_to category.name, category, :class =>"rotate" %>

		</li>
    <% end %>
    <% if user_signed_in? %>
    <li class="col-md auto-margin div-rotate">
      <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class =>"rotate" %>
    </li>
    <%else%>
    <li class="col-md auto-margin div-rotate">
      <%= link_to "Iniciar Sesión", new_user_session_path, :class =>"rotate"%>
    </li>
    <li class="col-md auto-margin div-rotate">
      <%= link_to "Crear Cuenta", new_user_registration_path, :class =>"rotate"%>
    </li>
    <%end%>
	</ul>
</nav>