config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :alumns do
    
    resources :comments
  end
  devise_for :users

  get 'show_list'=> "alumns#show_list",:as => "show_list"
  get 'show_timetable'=> "alumns#show_timetable",:as => "show_timetable"
  get 'show_resources'=> "alumns#show_resources",:as => "show_resources"


  get 'show_list_category'=> "categories#show_list_category",:as => "show_list_category"
  get 'show_menu'=> "categories#show_menu",:as => "show_menu"
  get 'show_timetable_comedor'=> "categories#show_timetable_comedor",:as => "show_timetable_comedor"
  get 'show_timetable_madrugadores'=> "categories#show_timetable_madrugadores",:as => "show_madrugadores"
  get 'show_timetable_tardones'=> "categories#show_timetable_tardones",:as => "show_timetable_tardones"
  get 'activities'=> "categories#activities",:as => "activities"
  get 'activities_tardones'=> "categories#activities_tardones",:as => "activities_tardones"
  get 'docs'=> "categories#docs",:as => "docs"

  #Esto es similar a escribir:
	  #get "/alumns" index
	  #post "/alumns" create
	  #delete "/alumns" delete
	  #get "/alumns/:id" show
	  #get "/alumns/new" new
	  #get "/alumns/:id/edit" edit
	  #patch "/alumns/:id" update
	  #put "/alumns/:id" update
  #
  #
  #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/alumn.rb
class Alumn < ApplicationRecord
	belongs_to :user
	has_and_belongs_to_many :categories
  has_many :comments, dependent: :delete_all
	validates :nombre, presence: true
	validates :apellido1, presence: true

	#after_create :save_categories  #callback del modelo
  #after_update :save_categories  #callback del modelo

	has_attached_file :cover, styles: { medium: "1280x720", thumb: "100x100>" }  #tiene un archivo adjunto que se llama cover
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  	

  	#custom setter, le asignamos valor al atributo (se ve por el =)
  	# def categories=(value)
  	# 	@categories = value
  	# end
    def self.main_columns
    %i(
       id
       nombre
       apellido1
       apellido2
       mother_phone
       father_phone
       direccion
       alergias
       )
    end
    
    def self.to_csv
      attributes = %w{Identificador Nombre Apellido Apellido Teléfono(madre) Teléfono(padre) Dirección Alergias}
       CSV.generate(col_sep:';', encoding:'ISO-8859-1') do |csv|
         csv << attributes
          all.each do |alumn|
            csv << self.main_columns.map{ |attr| alumn.send(attr) }
          end
      end
  end
  
	private
	#Es el callback, guarda las categorias. Crea registros de la tabla has categories, asignamos el campo de la categoria y el del alumno
  	# def save_categories
   #    unless @categories.blank?
  	# 	  @categories.each do|category_id|
  	# 		 HasCategory.create(category_id: category_id,alumn_id: self.id)
  	# 	  end
   #    end
  	# end
end

app/controllers/alumns_controller.rb
class AlumnsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_alumn, except: [:index, :new, :create, :show_list, :show_timetable, :show_resources]

	def index
		
	end

	def show
		@comment= Comment.new		
	end

	def new
		@alumn= Alumn.new
		@categories = Category.all
	end

	def edit
		
	end

	def create
		if @alumn.save
			redirect_to @alumn
		else
			render :new
		end
	end

	def destroy
	 #DELETE FROM articles
    	@alumn = Alumn.find(params[:id])
    	@alumn.destroy # Destroy eliminar el objeto de la BD
    	redirect_to show_list_path
	end

	def update
		#@alumn.categories = params[:categories]
		
		if @alumn.update(alumn_params)
			redirect_to @alumn
		else
			render :edit
		end
	end

	def show_timetable

	end

	def show_resources

	end

	def show_list
		@alumns= Alumn.all

		respond_to do |format|
      		format.html
      		format.csv { send_data @alumns.to_csv, filename: "alumns-#{Date.today}.csv" }
   		end
	end

	

	private #Métodos privados del controlador 
	def set_alumn
		@alumn= Alumn.find(params[:id])
	end

	def validate_user
		redirect_to new_user_session_path, notice: "Es necesario iniciar sesión para continuar"
	end

	def alumn_params #aqui ponemos los datos que el usuario puede escribir, lo que sean sensibles no se ponene aqui
		params
		.require(:alumn)
		.permit(
			:nombre,
			:apellido1,
			:apellido2,
			:mother_phone,
			:father_phone,
			:direccion,
			:alergias,
			:cover, 
			:categories,
			:category_ids=>[])
	end	
end

app/helpers/alumns_helper.rb
module AlumnsHelper
end

app/views/alumns/_form.html.erb
<%= form_for(@alumn) do |f| %>
	<% @alumn.errors.full_messages.each do |message| %>
		<div class="be-red white">
			 <%= message%>
		</div>
	<%end%>
	<div class="row index-box">
	    <div class="col-md-1" style="background: #c2ef6b;"></div>
	     <div class="col-md-10">
	     	<div class="row">
	     		<div class="col-md-5 center-xs">
					<h3 style="text-decoration: underline">Datos personales </h3>
					<p class="lbl_format end-xs">Nombre: <%= f.text_field :nombre, placeholder: "Nombre" , :class => "form_control "%></p>
					<p class="lbl_format end-xs">Apellido 1: <%= f.text_field :apellido1, placeholder: "Apellido 1" , :class => "form_control" %></p>
					<p class="lbl_format end-xs">Apellido 2: <%= f.text_field :apellido2, placeholder: "Apellido 2" , :class => "form_control" %></p>
					<p class="lbl_format end-xs">Teléfono Madre: <%= f.text_field :mother_phone, placeholder: "Teléfono" , :class => "form_control" %></p>
					<p class="lbl_format end-xs">Teléfono Padre: <%= f.text_field :father_phone, placeholder: "Teléfono" , :class => "form_control" %></p>
					<p class="lbl_format end-xs">Dirección: <%= f.text_area :direccion, placeholder: "Dirección" , :class => "form_control" %></p>
					<p class="lbl_format end-xs">Alergias: <%= f.text_area :alergias, placeholder: "Alergias" , :class => "form_control" %></p>
				</div>

				<div class="col-md-7">
					<div class="row center-xs">
						<div class="col-md-12">
							<h3 style="text-decoration: underline">Fotografia</h3>
						</div>
						<div class="col-md-12">
							<% unless @alumn.id.blank? %>
								<% if @alumn.cover.blank?%>
									<p class="lbl_format" style="color:red">*Actualmente no tiene ninguna fotografía</p>
								<% else%>
									<p class="lbl_format" style="color:green">*Ya existe una fotografía asociada a este alumno. </p>
								<%end%>
							<%end %>
							<%= f.file_field :cover%> 
						</div>
					</div>
					<div class="row center-xs">
						<div class="col-md-12">
							<h3 style="text-decoration: underline">Opciones:</h3>
						</div>
						<div class="col-md-6">
							<% @categories.each do |category| %>
								<% if @alumn.categories.include?(category) %>
									<div class="check row lbl_format"><%= check_box_tag "alumn[category_ids][]", category.id, checked: true%> <%= category.name%></div>
								<% else %>
									<div class="check row lbl_format"><%= check_box_tag "alumn[category_ids][]", category.id%> <%= category.name%></div>
								<%end%>
							<% end %>
						</div>
					</div>
				</div>
	     	</div>
	     	<div class="row center-xs">
	     		<div class="col-md-12 center-xs" >
			<br>
			<%= f.submit "Guardar", :class => 'btn-primary'%>
		</div>
	     	</div>
	    </div>
	  	<div class="col-md-1" style="background: #c2ef6b;"></div>
	</div>
<%end%>

app/views/alumns/edit.html.erb
<h1 class="center-xs text-title">Editar Alumno</h1>
<%= render "form" %>

app/views/alumns/index.html.erb
		<h1 class="row center-xs text-title">Gestión</h1>

<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<div class="row center-xs">
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("listado-inscritos-dibujo.png", :class => "img", :alt => "Imagen listado", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to "ADMINISTRAR ALUMNOS", show_list_path %></div>
				</div>
				 
			</div>
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("descargar.png", :class => "img", :alt => "Imagen descargar", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to "DESCARGAR LISTADO", show_list_path(format: "csv") %></div>
				</div> 
			</div>
		</div>
		<div class="row center-xs">
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("horario.png", :class => "img", :alt => "Imagen horario", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to "HORARIOS", show_timetable_path%></div>
				</div>
			</div>
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("recursos.jpg", :class => "img", :alt => "Imagen recursos", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to "RECURSOS", show_resources_path %></div>
				</div>
			</div>
		</div>
		<div class="row center-xs">
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("categoria.png", :class => "img", :alt => "Imagen categorías", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to 'VER CATEGORÍAS', categories_path %></div>
				</div>
			</div>
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("docs.png", :class => "img", :alt => "Imagen documentos", :style => "width:100px; height:60px;padding: 5px;") %>
              		<div class="text"><%= link_to "DOCUMENTOS", docs_path %></div>
				</div>
			</div>
		</div>
		<div class="row center-xs">
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("mas.jpg", :class => "img", :alt => "Imagen categorías", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to 'NUEVA CATEGORÍA', new_category_path() %></div>
				</div>
			</div>
		</div>

		
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>
	

	

app/views/alumns/new.html.erb
<h1 class="row center-xs text-title">Nuevo Alumno</h1>
<%= render "form" %>

app/views/alumns/show.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<div class=" row">
			<div class="center-xs col-md-12">
				<h1>Datos personales</h1>
			</div>
			<div class="row">
				<div class=" col-md-2" style="margin: 0px 10px;">
					<%= image_tag @alumn.cover.url(:thumb), :class => 'img_photo'%>
				</div>
				<div class="col-md-6 body_content">
					<p class="lbl_format"><span style="font-weight: bold;">Nombre Completo:</span> <%= @alumn.nombre %> <%= @alumn.apellido1%> <%= @alumn.apellido2 %></p>
					<p class="lbl_format"><span style="font-weight: bold;">Teléfono Madre:</span> <%= @alumn.mother_phone%></p>
					<p class="lbl_format"><span style="font-weight: bold;">Teléfono Padre:</span> <%= @alumn.father_phone%></p>
					<p class="lbl_format"><span style="font-weight: bold;">Dirección:</span> <%= @alumn.direccion%></p>
					<p class="lbl_format"><span style="font-weight: bold;">Alergias:</span> <%= @alumn.alergias%></p>
				</div>
				<div class="col-md-3">
					<div class="row center-xs">
						<p class="lbl_format col-md-12" style="font-weight: bold;">Inscrito en:</p>
					</div>
					<div class="row center-xs">
						<div class="col-md-12">
							<% @alumn.categories.each do |category| %>		
								<button class="btn-primary" style= "padding: 5px;"><%= link_to category.name, category %></button>
								<br>
							<% end %>
						</div>
					</div>
				</div>
			</div>		
		</div>

		<div class="row" style="background:#c2ef6b;height: 10px; margin:20px;"></div>

		<div class="row">
			<div class="col-md-6 center-xs">
				<h3>Comentarios <i class="fa fa-comments-o" style="font-size:35px"></i></h3>
				<div class="row comment-box">
					<% if @alumn.comments.count > 0 %>
						<% @alumn.comments.each do |comment| %>
							<div class="col-md-12"     margin-bottom: 10px;>
								<div class="row">
									<%= label_tag comment.updated_at.to_date.strftime("%d-%m-%Y"), nil, class: 'lbl_format_date col-md-4'%>
								</div>
								<div class="row">
									<%= label_tag comment.body, nil, class: 'lbl_format col-md-12'%>
								</div>
								<div class="row">
		       						<button class="col-md-2 comment-button">
										<%= link_to [comment.alumn, comment],method: :delete, :data => { :confirm => '¿Estas seguro de eliminar el registro?' } do %>
  											<i class="fa fa-trash" style="font-size:20px"></i>
										<% end %>
									</button>
		       					</div>
							</div>
						<% end %>
					<% else %>
						<%= label_tag "No existen comentarios", nil, class: 'lbl_format col-md-12'%>
					<% end %>
				</div>
			</div>
			<div class="col-md-6 center-xs">
				<h3 class="col-md-12">Nuevo Comentario</h3>
				<%= render "comments/form" %>			
			</div>
		</div>
		<div class="row">
			<% unless @alumn.user.nil? %>
				<p class="col-md-12 lbl_format center-xs">Alumno añadido por <%= @alumn.user.email%></p>
			<%end%>
		</div>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/alumns/show_list.html.erb
<div class="row index-box">
	<div class="col-md-12">
		<h1 class="row center-xs text-title">Alumnos Matriculados - 2017/2018</h1>
		<div class="row">
			<div class="col-md-12 center-xs ">
				<% @alumns.each do |alumn| %>
					<table class="row center-xs">
						<td class="body-content"><%= alumn.nombre %> <%= alumn.apellido1%> <%= alumn.apellido2%></td>	
						<th>
							<button class="btn-actions">
								<%= link_to alumn do %>
  									<i class="fa fa-eye tooltip" style="font-size:24px"><span class="tooltiptext">Ver Alumno</span></i>
								<% end %>
							</button>
						</th>
						<th>
							<button class="btn-actions">
								<%= link_to edit_alumn_path(alumn) do %>
  									<i class="fa fa-pencil tooltip" style="font-size:24px"><span class="tooltiptext">Editar Alumno</span></i>
								<% end %>
							</button>
						</th>
						<th>
							<button class="btn-actions">
								<%= link_to alumn,method: :delete, :data => { :confirm => '¿Estas seguro de eliminar el registro?' } do %>
  									<i class="fa fa-trash tooltip" style="font-size:24px"><span class="tooltiptext">Eliminar Alumno</span></i>
								<% end %>
							</button>
						</th>
					</table>
				<%end%>
			</div>
		</div>
		<div class="row center-xs">
			<div class="col-md-4"></div>
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<button class="btn-primary col-md-10"><%= link_to "Añadir Alumno", new_alumn_path()%></button>
			</div>	
		</div>
	</div>
</div>

app/views/alumns/show_resources.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<h1 class="row center-xs">Recursos para monitores de comedor</h1>
		<h3 class="row center-xs h3title">Objetivos Principales</h3>
		<div class="row">
			<div class="col-md-6 objetivos" >
				<p>1. Jugar con las niñas/os para desarrollar el espíritu</p>
				<p>2. Fomentar aptitudes cooperativas nos llevará a fomentar el compañerismo.</p>
				<p>3. Acercar otras culturas.</p>
				<p>4. Potenciar el sentido de la solidaridad.</p>
				<p>5. Fomentar la convivencia y el respeto hacia los demás para erradicar conductas violentas.</p>
			
			</div>
			<div class="col-md-6 objetivos" >
				<p>6. Desarrollar la capacidad crítica de interpretar el mundo.</p>
				<p>7. Promover el espíritu emprendedor y la capacidad expresiva.</p>
				<p>8. Motivar a las niñas/os hacia el cumplimiento del deber y la responsabilidad de sus tareas.</p>
				<p>9. Acercar las problemáticas sociales y medioambientales.</p>
			</div>
		</div>
		<h3 class="row center-xs h3title">Actividades</h3>
		<div class="row">
			<div class="col-md-1">
				
			</div>
			<div class="col-md-11 objetivos" >
				<p>Aquí hay un listado de enlaces con diferentes propuestas de actividades para el horario de comedor.</p>
				<p>https://es.slideshare.net/cagerico/proyecto-comedor-escolar-20132014</p>
				<p>http://www.convega.com/cpantoniosequeros/actividadescomedor.html</p>
				<p>http://www.marianoserra.net/?page_id=2440</p>
			</div>
		</div>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/alumns/show_timetable.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<h1 class="row center-xs text-title">Horario Escolar - 2017/2018</h1>
		<center>
		<table BORDER class="horario">        
			<tr>
			<td><TH>LUNES</TH><TH>MARTES</TH><TH>MIERCOLES</TH><TH>JUEVES</TH><TH>VIERNES</TH></td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>7:30/9:00</TH><td>Actividades y desayuno</td><td>Actividades y desayuno</td><td>Actividades y desayuno</td><td>Actividades y desayuno</td><td>Actividades y desayuno</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>9:00/10:00</TH><td>Gimnasia</td><td>Inglés</td><td>Gimnasia</td><td>Inglés</td><td>Gimnasia</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>10:00/11:00</TH><td>Inglés</td><td>Juegos  y lectura</td><td>Juegos  y lectura</td><td>Juegos  y lectura</td><td>Juegos  y lectura</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>11:00/11:30</TH><td>Almuerzo</td><td>Almuerzo</td><td>Almuerzo</td><td>Almuerzo</td><td>Almuerzo</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>11:30/12:30</TH><td>Juegos  y lectura</td><td>Inglés</td><td>Juegos  y lectura</td><td>Juegos  y lectura</td><td>Juegos  y lectura</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>12:30/14:00</TH><td>Comida y juegos</td><td>Comida y juegos</td><td>Comida y juegos</td><td>Comida y juegos</td><td>Comida y juegos</td>
			</tr>

		</table>
		</center>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>