config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :alumns do
    
    resources :comments
  end
  devise_for :users

  get 'show_list'=> "alumns#show_list",:as => "show_list"
  get 'show_timetable'=> "alumns#show_timetable",:as => "show_timetable"
  get 'show_resources'=> "alumns#show_resources",:as => "show_resources"


  get 'show_list_category'=> "categories#show_list_category",:as => "show_list_category"
  get 'show_menu'=> "categories#show_menu",:as => "show_menu"
  get 'show_timetable_comedor'=> "categories#show_timetable_comedor",:as => "show_timetable_comedor"
  get 'show_timetable_madrugadores'=> "categories#show_timetable_madrugadores",:as => "show_madrugadores"
  get 'show_timetable_tardones'=> "categories#show_timetable_tardones",:as => "show_timetable_tardones"
  get 'activities'=> "categories#activities",:as => "activities"
  get 'activities_tardones'=> "categories#activities_tardones",:as => "activities_tardones"
  get 'docs'=> "categories#docs",:as => "docs"

  #Esto es similar a escribir:
	  #get "/alumns" index
	  #post "/alumns" create
	  #delete "/alumns" delete
	  #get "/alumns/:id" show
	  #get "/alumns/new" new
	  #get "/alumns/:id/edit" edit
	  #patch "/alumns/:id" update
	  #put "/alumns/:id" update
  #
  #
  #
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :user, :optional => true
	validates :name, presence: true, uniqueness: true #obliga a que cada categoria tenga un nombre único
	has_and_belongs_to_many :alumns
	#relacionamos category - hasCategory - Alumn, para llegar de alumn hay que hacerlo through has_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoría creada correctamente' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoría modificada correctamente' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_list_category
    @category = Category.find(params[:id])
  end

  def show_menu
    
  end

  def show_timetable_comedor
   
  end

  def show_timetable_madrugadores
   
  end

  def show_timetable_tardones
   
  end

  def destroy


    
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoría eliminada correctamente' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :color,:alumn_ids=>[])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row"> 
    <div class="col-md-12 center-xs ">
      <div class="field">
        <h3>Nombre: <%= form.text_field :name, id: :category_name, class: "form_control" %></h3>
        
      </div>
    </div>
    <div class="col-md-12 center-xs ">
      <div class="field">
        <h3>Referencia: <%= form.color_field :color, id: :category_color %></h3>
        
      </div>
    </div>
    
    <div class="col-md-12 center-xs">
      <br>
      <%= form.submit "Guardar", :class => 'btn-primary' %>
    </div>
  </div>
<% end %>

app/views/categories/activities.html.erb
ACTIVIDADES AQUÍ

app/views/categories/activities_tardones.html.erb
ACTIVIDADES AQUÍ

app/views/categories/docs.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<div class="row center-xs">
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("descargar.png", :class => "img", :alt => "Imagen descarga", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to "INSCRIPCIÓN EXTRAESCOLARES", "http://www.ampacolegioalhambra.org/IMG/pdf/Inscr_AE_N4-2.pdf"%></div>
				</div>
			</div>
		</div>
		<div class="row center-xs">
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("descargar.png", :class => "img", :alt => "Imagen descarga", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to "SOLICITUD DE INSCRIPCIÓN", "https://www.tramitacastillayleon.jcyl.es/web/jcyl/binarios/795/162/IAPA%20985%20Solicitud%20v20.pdf?blobheader=application%2Fpdf%3Bcharset%3DUTF-8&blobheadername1=Cache-Control&blobheadername2=Expires&blobheadername3=Site&blobheadervalue1=no-store%2Cno-cache%2Cmust-revalidate&blobheadervalue2=0&blobheadervalue3=Portal_Informador&blobnocache=true"%></div>
				</div>
			</div>
			<div class="col-md-5 box-menu">
				<div class="div-img hidden" >
					<%= image_tag("descargar.png", :class => "img", :alt => "Imagen descarga", :style => "width:60px; height:60px;padding: 5px;") %>
					<div class="text"><%= link_to "NOTIFICACIÓN PADRES", "http://www.camposdelrio.es/wp-content/uploads/2011/11/Informacion-Para-Padres.pdf" %></div>
				</div>
				 
			</div>
			
		</div>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

<button class="btn-primary" ><%= link_to 'Ver Categoría', @category %></button>
<button class="btn-primary" ><%= link_to 'Volver', categories_path %></button>

app/views/categories/index.html.erb
<div class="row index-box">
  <p id="notice text" style="text-align: center;"><%= notice %></p>
  <div class="col-md-12">
    <h1 class="row center-xs">Categorías del Menú de Navegación</h1>
    <div class="row">
      <div class="col-md-12 center-xs ">
        <% @categories.each do |category| %>
        <table class="row center-xs">
            <td class="body-content"><%= category.name %></td> 
            <th>
              <button class="btn-actions">
                <%= link_to category do %>
                    <i class="fa fa-eye tooltip" style="font-size:24px"><span class="tooltiptext">Ver Categoría</span></i></i>
                <% end %>
              </button>
            </th>
            <th>
              <button class="btn-actions">
                <%= link_to edit_category_path(category) do %>
                    <i class="fa fa-pencil tooltip" style="font-size:24px"><span class="tooltiptext">Editar Categoría</span></i></i>
                <% end %>
              </button>
            </th>
            <th>
              <button class="btn-actions">
                <%= link_to category,method: :delete, :data => { :confirm => '¿Estas seguro de eliminar el registro?' } do %>
                    <i class="fa fa-trash tooltip" style="font-size:24px"><span class="tooltiptext">Eliminar Categoría</span></i>
                <% end %>
              </button>
            </th>
          </table> 
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1 class="center-xs">Nueva categoría</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1 class="row center-xs text-title"><%=@category.name%></h1>
<div class="row index-box">
  <div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
    <div class="row center-xs">
      <div class="col-md-5 box-menu">
        <div class="div-img hidden" >
          <%= image_tag("listado-inscritos-dibujo.png", :class => "img", :alt => "Imagen listado", :style => "width:60px; height:60px;padding: 5px;") %>
          <div class="text"><%= link_to "VER ALUMNOS", show_list_category_path(:id => @category.id.to_s) %></div>
        </div>

      </div>
      <div class="col-md-5 box-menu">
        <div class="div-img hidden" >
          <% if @category.id==1 %>
            <%= image_tag("cubiertos.png", :class => "img", :alt => "Imagen menu", :style => "width:60px; height:60px;padding: 5px;") %>
            <div class="text"><%= link_to "MENÚ DEL MES", show_menu_path %></div>
          <% end %>
          <% if @category.id==2 %>
            <%= image_tag("actividad.png", :class => "img", :alt => "Imagen actividades", :style => "width:60px; height:60px;padding: 5px;") %>
            <div class="text"><%= link_to "ACTIVIDADES DEL MES", "https://ampatrinitariassalamanca.files.wordpress.com/2015/11/actividades-en-servicio-de-madrugadores.pdf" %></div>
          <% end %>
          <% if @category.id==3 %>
            <%= image_tag("actividad.png", :class => "img", :alt => "Imagen actividades", :style => "width:60px; height:60px;padding: 5px;") %>
            <div class="text"><%= link_to "ACTIVIDADES DEL MES", "http://www.ampavargasllosa.com/wp-content/uploads/2016/06/MARIO-VARGAS-LLOSA.pdf" %></div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row center-xs">
      <div class="col-md-5 box-menu">
        <div class="div-img hidden" >
          <% if @category.id==1 %>
            <%= image_tag("horario.png", :class => "img", :alt => "Imagen horario", :style => "width:60px; height:60px;padding: 5px;") %>
            <div class="text"><%= link_to "HORARIOS", show_timetable_comedor_path%></div>
          <% end %>
          <% if @category.id==2 %>
              <%= image_tag("horario.png", :class => "img", :alt => "Imagen horario", :style => "width:60px; height:60px;padding: 5px;") %>
            <div class="text"><%= link_to "HORARIOS", show_madrugadores_path%></div>
            <% end %>
            <% if @category.id==3 %>
              <%= image_tag("horario.png", :class => "img", :alt => "Imagen horario", :style => "width:60px; height:60px;padding: 5px;") %>
            <div class="text"><%= link_to "HORARIOS", show_timetable_tardones_path%></div>
            <% end %>
        </div>
      </div>

      <div class="col-md-5 box-menu">
        <div class="div-img hidden" >
          <%= image_tag("categoria.png", :class => "img", :alt => "Imagen categoria", :style => "width:60px; height:60px;padding: 5px;") %>
          <div class="text"><%= link_to "EDITAR CATEGORÍA", edit_category_path(@category)%></div>
        </div>
      </div>


    </div>
  
  </div>
  <div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/categories/show_list_category.html.erb
<div class="col-md-12">
    <div class="row  center-xs">
      <p id="notice text" style="text-align: center;"><%= notice %></p>
      
    </div>
  </div>

<div class="row index-box">
    <div class="col-md-1" style="background: #c2ef6b;"></div>
      <div class="col-md-10">
        <div class="row center-xs">
          <p id="notice text" style="text-align: center;"><%= notice %></p>
          <h1 class="center-xs">Alumnos inscritos en <%= @category.name %></h1>
        </div>
      <div class="row">
        <div class="col-md-12 center-xs">
          <% @category.alumns.each do |alumn| %>
            <table class="row center-xs">       
              <td class="lbl_format" style="width:500px;"><%= link_to "#{alumn.nombre} #{alumn.apellido1} #{alumn.apellido2}", alumn%></td>
            </table>
          <%end%>
        </div>
      </div>
    </div>
  <div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/categories/show_menu.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<h1 class="row center-xs text-title">Menú Diciembre 2018</h1>
		<center>
		<table BORDER class="horario">        
			<tr>
			<td><TH>PRIMERO</TH><TH>SEGUNDO</TH><TH>POSTRE</TH><TH>VALOR ENERGÉTICO</TH></td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>Día 1</TH><td>Sopa de cocido</td><td>Cocido completo</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 2</TH><td>Macarrones Boloñesa</td><td>Muslitos de pollo en salsa</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 3</TH><td>Alubias blancas</td><td>Filete de ternera</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 4</TH><td>Arroz con tomate</td><td>Salmón al horno</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 5</TH><td>Lentejas con chorizo</td><td>Merluza</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 6</TH><td>Tallarines matriciana</td><td>Lomo al ajillo</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 7</TH><td>Judías verdes</td><td>Trotilla de patata</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 8</TH><td>Macarrones Boloñesa</td><td>Muslitos de pollo en salsa</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 9</TH><td>Judías verdes</td><td>Trotilla de patata</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 10</TH><td>Sopa de cocido</td><td>Cocido completo</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 11</TH><td>Judías verdes</td><td>Trotilla de patata</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 12</TH><td>Macarrones Boloñesa</td><td>Muslitos de pollo en salsa</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 13</TH><td>Judías verdes</td><td>Trotilla de patata</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 14</TH><td>Sopa de pescado</td><td>Albóndigas</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 15</TH><td>Judías verdes</td><td>Trotilla de patata</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 16</TH><td>Tallarines matriciana</td><td>Lomo al ajillo</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 17</TH><td>Arroz con tomate</td><td>Salmón al horno</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 18</TH><td>Sopa de pescado</td><td>Albóndigas</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 19</TH><td>Judías verdes</td><td>Trotilla de patata</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 20</TH><td>Sopa de cocido</td><td>Cocido completo</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 21</TH><td>Judías verdes</td><td>Trotilla de patata</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 22</TH><td>Arroz con tomate</td><td>Salmón al horno</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 23</TH><td>Lentejas con chorizo</td><td>Merluza</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 24</TH><td>Tallarines matriciana</td><td>Lomo al ajillo</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 25</TH><td>Alubias blancas</td><td>Filete de ternera</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 26</TH><td>Sopa de pescado</td><td>Albóndigas</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 27</TH><td>Arroz con tomate</td><td>Salmón al horno</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 28</TH><td>Tallarines matriciana</td><td>Lomo al ajillo</td><td>Lácteo</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 29</TH><td>Lentejas con chorizo</td><td>Merluza</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 30</TH><td>Sopa de pescado</td><td>Albóndigas</td><td>Fruta</td><td>453 KCal</td>
			</tr>
			<tr ALIGN=CENTER>    
			<TH>Día 31</TH><td>Alubias blancas</td><td>Filete de ternera</td><td>Fruta</td><td>453 KCal</td>
			</tr>

		</table>
		</center>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/categories/show_timetable_comedor.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<h1 class="row center-xs text-title">Horario Comedor - 2017/2018</h1>
		<center>
		<table BORDER class="horario">        
			<tr>
			<td><TH>LUNES</TH><TH>MARTES</TH><TH>MIERCOLES</TH><TH>JUEVES</TH><TH>VIERNES</TH></td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>Desayuno</TH><td>8:00 / 9:00</td><td>8:00 / 9:00</td><td>8:00 / 9:00</td><td>8:00 / 9:00</td><td>8:00 / 9:00</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>Almuerzo</TH><td>11:00 / 11:30</td><td>11:00 / 11:30</td><td>11:00 / 11:30</td><td>11:00 / 11:30</td><td>11:00 / 11:30</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>Comida</TH><td>13:00 / 14:00</td><td>13:00 / 14:00</td><td>13:00 / 14:00</td><td>13:00 / 14:00</td><td>13:00 / 14:00</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>Merienda</TH><td>17:30 / 18:00</td><td>17:30 / 18:00</td><td>17:30 / 18:00</td><td>17:30 / 18:00</td><td>17:30 / 18:00</td>
			</tr>

		</table>
		</center>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/categories/show_timetable_madrugadores.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<h1 class="row center-xs text-title">Horario Madrugadores - 2017/2018</h1>
		<center>
		<table BORDER class="horario">        
			<tr>
			<td><TH>LUNES</TH><TH>MARTES</TH><TH>MIERCOLES</TH><TH>JUEVES</TH><TH>VIERNES</TH></td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>7:30/8:00</TH><td>Desayuno</td><td>Desayuno</td><td>Desayuno</td><td>Desayuno</td><td>Desayuno</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>8:00/8:30</TH><td>Gimnasia</td><td>Cuentacuentos</td><td>Juego libre</td><td>Juegos interactivos</td><td>Juego libre</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>8:30/9:00</TH><td>Juego libre</td><td>Juego libre</td><td>Juegos conjuntos</td><td>Juego libre</td><td>Gimnasia</td>
			</tr>

		</table>
		</center>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>

app/views/categories/show_timetable_tardones.html.erb
<div class="row index-box">
	<div class="col-md-1" style="background: #c2ef6b;"></div>
	<div class="col-md-10">
		<h1 class="row center-xs text-title">Horario Tardones - 2017/2018</h1>
		<center>
		<table BORDER class="horario">        
			<tr>
			<td><TH>LUNES</TH><TH>MARTES</TH><TH>MIERCOLES</TH><TH>JUEVES</TH><TH>VIERNES</TH></td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>17:30/18:00</TH><td>Merienda</td><td>Merienda</td><td>Merienda</td><td>Merienda</td><td>Merienda</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>18:00/18:30</TH><td>Gimnasia</td><td>Cuentacuentos</td><td>Juego libre</td><td>Juegos interactivos</td><td>Juego libre</td>
			</tr>

			<tr ALIGN=CENTER>    
			<TH>18:30/19:00</TH><td>Juego libre</td><td>Juego libre</td><td>Juegos conjuntos</td><td>Juego libre</td><td>Gimnasia</td>
			</tr>

		</table>
		</center>
	</div>
	<div class="col-md-1" style="background: #c2ef6b;"></div>
</div>